### ISSUE TITLE
Update GitHub links that mention MERLTech on the MERL Center website by merging the draft pr

### ISSUE THREAD

**Issue by Rabia2219** [MERLTech/MERL-Center-public#113]
### Overview
We need to update any links that reference github.com/MERLTech on the MERL Center website to either be relative or point to github.com/merlcenter

### Action Items
- [x] identify and document all the places where MERL Tech appears on the website
- [x] determine which ones need to be updated and how
- [x] do a pr to make the necessary changes and put it in draft mode so that we can hold off on merging it until the github org is renamed.

### Resources/Instructions

- https://merlcenter.org/about/
- https://github.com/search?q=repo%3AMERLTech%2FMERL-Center-public%20github.com%2Fmerltech&type=code

**Comment by MattPereira** [comment]
# Documentation

### Contributing.md
- Several links to different markdown files on our repository

### README.md
- Links to `MERLdefnition.md` and `Contributing.md`

### _guides/2020-12-08-open-source-merl-workflows.md
- Link to `MERLdefnition.md`

### _guides/2021-04-23-Dispelling-myths-qualifying-assumptions.md
- Link to `MERLdefnition.md`

### _includes/header.html
- The `View the Repository` link that appears in the navbar on desktop viewport
- The `View the Repository` link that appears in the mobile drawer

### about.html
- All the links that show in "THE SCOPE OF THE MERL CENTER" section
![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/b0acb5a8-ded8-46c7-814e-17da468fbfe7)
