### ISSUE TITLE
Add Developer Guide

### ISSUE THREAD

**Issue by MattPereira** [MERLTech/MERL-Center-public#117]
### Overview
We want to make it easy for developers to get started with running our Jekyll site on their local machine

### Action Items
- [x] How to set up dev environment
- [x] How to create a pull request
- [x] How to review a pull request

### Resources
- https://www.ruby-lang.org/en/documentation/installation/
- https://nodejs.org/en/download

<details><summary>See screenshot</summary>

![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/fb0ac86f-54fe-4cab-b19a-a2762d9ee703)

</details>
<details><summary>See screenshot</summary>

![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/0dddd8a1-76eb-4f8f-9804-1ca47f66d2a2)
</details>

![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/8f91b2d2-8c68-44af-8ae9-caf0ca2ee9cb)

<details><summary>See screenshot</summary>

![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/4f467adc-a296-4e00-8f6e-09a3dffcc208)

</details>

**Comment by MattPereira** [comment]
<details><summary>Feedback Options</summary>

![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/08d7322b-2947-49f1-b0d2-f7e7d31719be)

</details>

**Comment by MattPereira** [comment]
<details><summary>See screenshot</summary>

![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/99d863c1-2245-4eb2-8f5c-4336422b9f33)

</details>

**Comment by MattPereira** [comment]
![image](https://github.com/MERLTech/MERL-Center-public/assets/73561520/6992b056-88d1-4024-8ec8-3b9b84a08b3c)

**Comment by ExperimentsInHonesty** [comment]
Please add instructions for installing Git, which is a prerequisite for contributing via command lime

these instructions came from hackforla.org website team contrib file

### **1.2 Dev setup (2): Installing Git**

Before cloning your forked repository to your local machine, you must have Git installed. You can find instructions for installing Git for your operating system [**here**](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git). Please note that if you have a Mac the page offers several options (see other option, if you need to conserve hard drive space) including:

- an “easiest” option (this version is fine for use at hackforla): This option would take just over 4GB.
- a “more up to date” option (not required but optional if you want it): This option prompts you to go to install an 8GB package manager called Homebrew. 
- Other option: If your computer is low on space, you can use this [tutorial](https://www.datacamp.com/community/tutorials/homebrew-install-use) to install XCode Command Tools and a lighter version of Homebrew and then install Git using this command: ```$ brew install git```  which in total only uses 300MB.
