### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Rabia2219** [MERLTech/MERL-Center-public#120]
Hi, 
We are cleaning up the MERL Center repository in order to make it easier for new members to navigate and avoid sending reminder messages for issues that you no longer want to work on. 
Please check the box(es) below and let us know if you are still interested in working on this issue and your role in the work product.

I'm @Rabia2219 , here's my status on this issue

- [ ] I'm interested in being the Lead Author
- [ ] I'm interested in being a Contributing Author
- [ ] I'm interested in being an Editor
- [ ] I no longer have time to work on this
- [ ] I don't have time to work on this now, but contact me when other people are actively working on it and I might be able to join then

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty are you getting this?

**Comment by Rabia2219** [comment]
### Response from GitHub Support

Hi Rabia,

Thank you for following up! Taking a look at those specific events, I can confirm that our system did send notifications consistent with the mentioned user's account settings. For example, users with only web notifications enabled received a web notification, while any with email set as their preferred delivery destination received an email. I have cross-referenced this with our email server logs and the email messages are indeed being sent successfully from our end. Your account will not have received any notification for the @mention in the first comment, as we don't send a notification for self-mentions from the same account.

I hope this information helps! Please let me know if you have any further questions at all.

Cheers,
Alex

**Comment by ExperimentsInHonesty** [comment]
This issue is complete.  It turns out they are just ignoring the messages they receive in email, if we email by @ mention.
