### ISSUE TITLE
Fallback image for author is not displayed when authorGitHubID is not available

### ISSUE THREAD

**Issue by aphilop** [MERLTech/MERL-Center-public#82]
**Problem description**

At the section `YOU MIGHT ALSO LIKE` at the bottom of an article, there is an instance where the fallback image for an author is not displayed because there is no `authorGitHubID` available (see image below).

![image](https://user-images.githubusercontent.com/102693686/168136828-4157a67d-3602-4bc4-b3b6-a696ae9a7a6a.png)

While there is a mechanism ([authorImg.html](https://github.com/MERLTech/MERL-Center-public/blob/main/_includes/authorImg.html)) to mitigate this, which is used in another places (Index page, Case Studies page, Guides page, after the title of an article), this mechanism is not used in this section.

**Solution**
Include [authorImg.html](https://github.com/MERLTech/MERL-Center-public/blob/main/_includes/authorImg.html) under the section `YOU MIGHT ALSO LIKE` in [blog-post.html](https://github.com/MERLTech/MERL-Center-public/blob/main/_layouts/blog-post.html).

**Comment by malakumar85** [comment]
@andrewrmn - another bug for you to look at, thanks!
