### ISSUE TITLE
Table rendering error

### ISSUE THREAD

**Issue by scoker-me** [MERLTech/MERL-Center-public#95]
Tables don't render correctly on article Open Source Usage in East Africa on the website:

![website table](https://user-images.githubusercontent.com/55405623/197804899-33b9ec26-b448-4c5b-b7ce-80731b37c09b.PNG)

They look fine in the original markdown file.

![markdown table](https://user-images.githubusercontent.com/55405623/197804938-f19d2ce2-c150-48be-8464-fe8ec806b4f8.PNG)

Any thoughts on why this might be happening and a fix?

**Comment by malakumar85** [comment]
@scoker-me - whatever markdown generator that's being used is adding a lot of unnecessary spaces and spacers for GitHub flavored markdown. Try this instead:

*Table 1: Survey sections and description*  

No. | Section | Description
---- | ------- | ------------ 
1   | About your organization | This section gathered information on the sector in which the participant worked  (e.g., public sector, private sector, academia, etc.), the geographical scope of the organization’s operations, and their thematic focus.                                                                                 
2   | Your role in the organization | This gathered information on the respondent’s experience in MERL and in their organization.                                         
3   | Tool usage  | This included questions on the tools used for data collection and management, data analysis and visualization, data reporting, and the organization’s general level of proficiency in those tools. In addition, it also asked questions on the tools’ cost and time efficiency, the challenges that the organization faced in using those tools, and the type of training that they received.
4   | Tool selection  | This section asked about the factors that organizations consider in selecting tools as well as people involved in the decision-making process.   
5   | Process assignment | This included questions on which staff are involved in each of the MERL processes.                                                             
6   | Familiarity with OSS | This section sought to gauge the respondent’s familiarity with OSS and whether they had alternatives to proprietary software.

**Comment by bonniewolfe** [comment]
My favorite markdown converter https://tabletomarkdown.com/convert-spreadsheet-to-markdown/
